add-global-variants="true"
no-hooks="true"
no-tests="true"

[psql]
dbname="sgpdb"
host="localhost"
user="yagpdb"
pass="ihateducks"
sslmode="disable"
whitelist=["reputation_configs", "reputation_users", "reputation_log", "reputation_roles"]