add-global-variants="true"
no-hooks="true"
no-tests="true"

[psql]
dbname="quackpdb"
host="localhost"
user="postgres"
pass="123"
sslmode="disable"
whitelist=["reputation_configs", "reputation_users", "reputation_log"]