add-global-variants="true"
no-hooks="true"
no-tests="true"

[psql]
dbname="sgpdb"
host="localhost"
user="yagpdb"
pass="ihateducks"
sslmode="disable"
whitelist=["rsvp_sessions", "rsvp_participants"]