add-global-variants="true"
no-hooks="true"
no-tests="true"

[psql]
dbname="sgpdb"
host="localhost"
user="sgpdb"
pass="ihateducks"
sslmode="disable"
whitelist=["ticket_configs", "tickets", "ticket_participants"]