add-global-variants="true"
no-hooks="true"
no-tests="true"

[psql]
dbname="syzygy"
host="localhost"
user="syzygy"
pass="ihateducks"
sslmode="disable"
whitelist=["ticket_configs", "tickets", "ticket_participants"]