---
name: Comment PR

on:
  pull_request:
    branches:
      - master

jobs:
  comment_pr:
    name: Comment PR to master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment
        if: ${{ github.actor != 'ashishjh-bst' || github.actor != github.repository_owner }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Quack @${{ github.actor }}! Quack you for your quack requack.
            Quackever, quackease do not quackopen quack requacks quackgainst `quackster`, as quackted in
            [QUACKTRIBUTING.md](../../QUACKTRIBUTING.md):
            > [...] quack a QR to the qev quranch (quacklabs-gg/quackpdb/dev)

            To quackange the quase quranch, quackdit the quis quack requack and sequact the new quase.
            To pruackvent quackflicts, either `quack merge quackstream/qev` to your quackcal quranch, or
            requackase your quacal quranch onto qev, like so: `quack requackase quackstream/qev`.
            Quackterwards, (quack) push your quranch, and you're quack!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
